name: hotel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.2.0
  get_it: ^7.6.6
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  email_validator: ^2.1.17
  flutter_multi_formatter: ^2.12.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  injectable_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/fonts/sf_pro/
   - assets/icons/
   - assets/images/

  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Thin.ttf
          weight: 100
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Ultralight.ttf
          weight: 300
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Light.ttf
          weight: 400
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Regular.ttf
          weight: 500
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Medium.ttf
          weight: 700
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Semibold.ttf
          weight: 900
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Bold.ttf
          weight: 500
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Heavy.ttf
          weight: 700
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Black.ttf
          weight: 900